//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlCommentSerialization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlCommentSerialization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} .
        /// </summary>
        internal static string CommentPadding {
            get {
                return ResourceManager.GetString("CommentPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string CommentWrap {
            get {
                return ResourceManager.GetString("CommentWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults to {0}.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize when instantiating Comment class using constructor without specifying parameters.
        /// </summary>
        internal static string ExceptionInvalidState {
            get {
                return ResourceManager.GetString("ExceptionInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call method Comment.WriteXml() passing null for parameter writer.
        /// </summary>
        internal static string ExceptionWriterNull {
            get {
                return ResourceManager.GetString("ExceptionWriterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}: {2}.
        /// </summary>
        internal static string Supplemental {
            get {
                return ResourceManager.GetString("Supplemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero or more elements of types {0}.
        /// </summary>
        internal static string TypeArrayMany {
            get {
                return ResourceManager.GetString("TypeArrayMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero or more elements of type {0}.
        /// </summary>
        internal static string TypeArrayOne {
            get {
                return ResourceManager.GetString("TypeArrayOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either true or false.
        /// </summary>
        internal static string TypeBoolean {
            get {
                return ResourceManager.GetString("TypeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte between {0} and {1}.
        /// </summary>
        internal static string TypeByte {
            get {
                return ResourceManager.GetString("TypeByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character between {0} and {1}.
        /// </summary>
        internal static string TypeChar {
            get {
                return ResourceManager.GetString("TypeChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal number between {0} and {1}.
        /// </summary>
        internal static string TypeDouble {
            get {
                return ResourceManager.GetString("TypeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of {0}.
        /// </summary>
        internal static string TypeEnum {
            get {
                return ResourceManager.GetString("TypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of {0}.
        /// </summary>
        internal static string TypeEnumFlags {
            get {
                return ResourceManager.GetString("TypeEnumFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the following {0}.
        /// </summary>
        internal static string TypeEnumSuffix {
            get {
                return ResourceManager.GetString("TypeEnumSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole number between {0} and {1}.
        /// </summary>
        internal static string TypeInt {
            get {
                return ResourceManager.GetString("TypeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer.
        /// </summary>
        internal static string TypeIntPtr {
            get {
                return ResourceManager.GetString("TypeIntPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole number between {0} and {1}.
        /// </summary>
        internal static string TypeSingle {
            get {
                return ResourceManager.GetString("TypeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric text between {0} and {1} characters.
        /// </summary>
        internal static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole positive number between {0} and {1}.
        /// </summary>
        internal static string TypeUInt {
            get {
                return ResourceManager.GetString("TypeUInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned Pointer.
        /// </summary>
        internal static string TypeUIntPtr {
            get {
                return ResourceManager.GetString("TypeUIntPtr", resourceCulture);
            }
        }
    }
}
